task :default => :console

task :console do
  ruby "-Ilib -S irb"
end

namespace :setup do
  task :elasticsearch do
    require_relative '../data-indexer/indexers.rb'
    client = ::Indexers::Elasticsearch.new(true)
  end
  task :transfer_data do
    require_relative '../lib/ecosystem-platform/jobs/data_transferer.rb'
    EcosystemPlatform::Jobs::DataTransferer.perform
  end
end

namespace :uploaders do
  namespace :numeracy do
    task :assessment do
      require_relative '../uploaders/numeracy/assessment.rb'
      Uploaders::Numeracy::Assessment.upload
    end
  end
end

namespace :cleaners do
  task :oe_summary do
    require_relative '../data-remover/oe_remover.rb'
    OERemover.remove('OE_SUMMARY')
  end
  task :ge_signup do
    require_relative '../data-remover/oe_remover.rb'
    require_relative '../data-remover/ge_signup_cleanup.rb'
    OERemover.remove('GE_SIGNUP')
    Removers::GeSignupCleanup.remove
  end
  task :child_flag_reseter do
    require_relative '../lib/ecosystem-platform/jobs/child_flag_reseter.rb'
    EcosystemPlatform::Jobs::ChildFlagReseter.perform
  end
end

namespace :correctors do
  task :event_signup_utype_correction do
    require_relative '../lib/ecosystem-platform/correctors/signup_utype_add.rb'
    EcosystemPlatform::Correctors::SignupUtypeAdd.perform
  end
  task :child_data_populator_for_false_flag do
    require_relative '../lib/ecosystem-platform/jobs/child_data_populator_for_false_flag.rb'
    EcosystemPlatform::Jobs::ChildDataPopulatorForFalseFlag.perform
  end
  task :remove_uid do
    require_relative '../lib/ecosystem-platform/correctors/remove_uid.rb'
    EcosystemPlatform::Correctors::RemoveUid.perform
  end
  task :remove_uekstep_id do
    require_relative '../lib/ecosystem-platform/correctors/remove_uekstep_id.rb'
    EcosystemPlatform::Correctors::RemoveUekstepId.perform
  end
  task :remove_by_device_id do
    require_relative '../lib/ecosystem-platform/correctors/remove_by_device_id.rb'
    EcosystemPlatform::Correctors::RemoveByDeviceId.perform
  end  
end

namespace :scheduled do
  task :reverse_search do
    require_relative '../data-async-processors/geo_reverse_search2.rb'
    require_relative '../data-indexer/indexers.rb'
    client = ::Indexers::Elasticsearch.new(false)
    # Processors::ReverseSearch.perform do |loc,ldata,hit|

    # end
    Processors::ReverseSearch2.perform
  end
  task :set_ldata do
    require_relative '../data-async-processors/set_ldata2.rb'
    require_relative '../data-indexer/indexers.rb'
    # Processors::SetLdata.perform
    Processors::SetLdata2.perform
  end
  task :generate_signup do
    require_relative '../data-async-processors/signup_processor.rb'
    # require_relative '../data-indexer/indexers.rb'
    Processors::SignupProcessor.perform
  end
  task :oe_summarize do
    require_relative '../data-async-processors/oe_summary_generator.rb'
    require_relative '../data-indexer/indexers.rb'
    client = ::Indexers::Elasticsearch.new(false)
    Processors::OeSummaryGenerator.perform
  end
  task :signup_geo_tag do
    require_relative '../data-async-processors/signup_geo_tagger.rb'
    require_relative '../data-indexer/indexers.rb'
    client = ::Indexers::Elasticsearch.new(false)
    Processors::SignupGeoTagger.perform
  end
  task :child_data_populator do
    require_relative '../lib/ecosystem-platform/jobs/child_data_populator.rb'
    EcosystemPlatform::Jobs::ChildDataPopulator.perform
  end
  task :generate_checksum do
    require_relative '../lib/ecosystem-platform/jobs/checksum_generator.rb'
    EcosystemPlatform::Jobs::ChecksumGenerator.perform
  end
end

namespace :generators do
  task :json_dump do
    require_relative '../data-generator/session_generator.rb'
    r = Generator::Runner.new({users:1,devices:1,sessions:1})
    r.run do |session,logger|
      session.events.each do |event|
        puts event
      end
    end
  end
  task :sessions do
    require_relative '../data-generator/session_generator.rb'
    require 'ruby-progressbar'
    client = ::Indexers::Elasticsearch.new(true)
    r = Generator::Runner.new
    time = 0
    bar = ProgressBar.create(total: Generator::SESSIONS)
    r.run do |session,logger|
      bar.increment
      session.events.each do |event|
        binding.pry
        # result = client.index('ecosystem-sample-identities','events_v1',event)
        result.merge!(event)
        logger.info "EVENT #{result.to_json}"
      end
    end
  end
end
