#!/bin/sh

MONIT_GROUP="[u'influxdb']"
MONIT_IP="{{ influxdb }}"
MONIT_DATE=`date`
COLOR=$1
DESCRIPTION=$2
/usr/bin/curl \
    -X POST \
    -s \
    --data-urlencode "payload={ \
        \"channel\": \"#{{ samza_slack_channel }}\", \
        \"username\": \"Influxdb-{{ env }}\", \
        \"pretext\": \"$MONIT_IP | $MONIT_GROUP | $MONIT_DATE\", \
        \"color\": \"$COLOR\", \
        \"icon_emoji\": \":bangbang:\", \
        \"text\": \"$DESCRIPTION\" \
    }" \
    {{ samza_alert_slack_url }}
