#!/bin/bash
#set -x
/usr/local/hadoop/bin/yarn application --list | awk '{print $1 " " $2 " " $6 " " $7 " " $9}' > running_jobs_live
job=`cat samza-job-string`
job_count_live=`grep -c application running_jobs_live`

if [[ "$job_count_live" -eq "{{ jobs_count }}" ]]; then
   /usr/local/hadoop/bin/yarn application --list | awk '{print $1 " " $2 " " $6 " " $7 " " $9}' > running_jobs_list
fi

job_count_list=`grep -c application running_jobs_list`

if [ $job_count_live == $job_count_list ]; then
   /usr/local/hadoop/bin/yarn application --list | awk '{print $1 " " $2 " " $6 " " $7 " " $9}' > running_jobs_list
fi

for i in $job
do 
  if ! grep -q $i running_jobs_live
  then
      failed_job="$i"
      failed_job_details=`grep $failed_job running_jobs_list`
      echo "$failed_job_details" | awk '{print $2}' | awk -F'.' '{print $2}' >> failed_jobs_details
      touch failed_jobs_details.tmp && chmod 666 failed_jobs_details.tmp
      sort -u failed_jobs_details > failed_jobs_details.tmp && mv failed_jobs_details.tmp  failed_jobs_details
      text=`echo job-is-not-running-$failed_job_details | sed 's/ /-/g; s/RUNNING/killed/g'`
      /usr/local/bin/samza_slack.sh critical $text
  fi
done

failed_job=`cat failed_jobs_details`

for i in $failed_job
do
  if grep -q $i running_jobs_live
  then
     running_job_details=`grep $i running_jobs_live`
     text=`echo job-is-back-to-running-$running_job_details | sed 's/ /-/g'`
     sed -i 's/'$i'//g; /^$/d ' failed_jobs_details
     /usr/local/bin/samza_slack.sh good $text
  fi
done
