#!/bin/sh

MONIT_GROUP="[u'dp-yarn', u'dp-yarn-master', u'ep', u'lp-yarn', u'lp-yarn-master', u'{{ env }}']"
MONIT_IP="{{ __yarn_host__ }}"
COLOR=$1
DESCRIPTION=$2
/usr/bin/curl \
    -X POST \
    -s \
    --data-urlencode "payload={ \
        \"channel\": \"#samzalogs-alert-test\", \
        \"username\": \"Monit\", \
        \"pretext\": \"$MONIT_IP | $MONIT_GROUP | $MONIT_DATE\", \
        \"color\": \"$COLOR\", \
        \"icon_emoji\": \":bangbang:\", \
        \"text\": \"$DESCRIPTION\" \
    }" \
    https://hooks.slack.com/services/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
